name: Sweet Home Costa Rica Documentary
favicon: null
layout_spectrum: 0.50396
typography_spectrum: 0.0607825662009418
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#0c0c0c'
    - '#555555'
    - '#9a9a9a'
    - '#c2c2c2'
  brandStrength: 0.75
  lightness: 0.05392536357976496
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
